alg:
    n_iter: 100000

agent:
    size: 100000
    epsilon: 0.05
    learning_starts: 1024
    learning_freq: 1
    target_update_freq: 1
    n_actions: 16

q_net:
    n_layers: 2
    input_size: 256
    n_input_channels: 4
    n_channels: 16
    stride: 1
    kernel_size: 5
    maxpool_kernel_size: 2
    activation: relu
    gamma: 0.99