alg:
    n_iter: 100000

env:
    threshold: 0.1
    max_timesteps: 5000
    
logger:
    average_over: 10

agent:
    size: 100000
    epsilon: 0.05
    learning_starts: 1024
    learning_freq: 1
    target_update_freq: 1
    
    q_net:
        n_layers: 2
        input_size: 480
        output_size: 64
        n_input_channels: 4
        n_channels: 16
        kernel_size: 5
        stride: 1
        padding: 0
        maxpool_kernel_size: 2
        activation: relu
        gamma: 0.99