alg:
    n_iter: 1000
    flush_frequency: 100
    use_gpu: True
    agent: ddpg

env:
    threshold: 0.05
    ee_collision_threshold: 0.15
    max_timesteps: 100

robot_arm:
    camera_tilt: 0.6
    delay: 0.5
    
logger:
    average_over: 10

dqn_agent:
    size: 1000
    epsilon: 0.5
    learning_starts: 10
    learning_freq: 1
    target_update_freq: 4
    batch_size: 4
    
    q_net:
        n_layers: 2
        input_size: 480
        n_input_channels: 4
        n_channels: 4
        kernel_size: 3
        stride: 1
        padding: 1
        activation: relu
        gamma: 0.99
        grad_norm_clipping: 10
        alg: ddqn

ddpg_agent:
    size: 1000
    noise: 1.0
    learning_starts: 10
    learning_freq: 1
    target_update_freq: 1
    batch_size: 4
    save_freq: 100
    load: False
    
    q_net:
        n_conv_layers: 3
        input_size: 480
        n_input_channels: 4
        n_channels: 4
        kernel_size: 3
        stride: 2
        padding: 1
        n_linear_layers: 2
        size: 32
        activation: tanh
        gamma: 0.99
        polyak_avg: 0.01
        lr: 0.00002
        grad_norm_clipping: 10

    actor_net:
      n_conv_layers: 3
      input_size: 480
      n_input_channels: 4
      n_channels: 4
      kernel_size: 3
      stride: 2
      padding: 1
      n_linear_layers: 2
      size: 32
      activation: tanh
      polyak_avg: 0.01
      lr: 0.000002
      grad_norm_clipping: 10