alg:
    n_iter: 1000
    flush_frequency: 100
    use_gpu: True
    agent: ddpg

env:
    threshold: 0.1
    max_timesteps: 10
    
logger:
    average_over: 10

dqn_agent:
    size: 100000
    epsilon: 0.5
    learning_starts: 10
    learning_freq: 1
    target_update_freq: 4
    batch_size: 4
    
    q_net:
        n_layers: 2
        input_size: 480
        n_input_channels: 4
        n_channels: 4
        kernel_size: 3
        stride: 1
        padding: 1
        activation: relu
        gamma: 0.99
        grad_norm_clipping: 10
        alg: ddqn

ddpg_agent:
    size: 100000
    noise: 0.5
    learning_starts: 10
    learning_freq: 1
    target_update_freq: 4
    batch_size: 4
    
    q_net:
        n_conv_layers: 3
        input_size: 480
        n_input_channels: 4
        n_channels: 4
        kernel_size: 3
        stride: 2
        padding: 1
        n_linear_layers: 2
        size: 32
        activation: tanh
        gamma: 0.99
        lr: 0.0001
        grad_norm_clipping: 10

    actor_net:
      n_conv_layers: 3
      input_size: 480
      n_input_channels: 4
      n_channels: 4
      kernel_size: 3
      stride: 2
      padding: 1
      n_linear_layers: 2
      size: 32
      activation: tanh
      lr: 0.00002
      grad_norm_clipping: 10